coverage:
  precision: 2
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        flags:
          - unit
          - application

ignore:
  - "api" # generated code
  - "applicationtest" # only tests
  - "store/migrations" # sql migrations
  - "server/swaggerui" # swaggerui artifacts
  - "telemetry" # telemetry stack files
