// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	HealthzOperation       OperationName = "Healthz"
	TasksGetOperation      OperationName = "TasksGet"
	TasksIDDeleteOperation OperationName = "TasksIDDelete"
	TasksIDGetOperation    OperationName = "TasksIDGet"
	TasksIDPutOperation    OperationName = "TasksIDPut"
	TasksPostOperation     OperationName = "TasksPost"
)
